In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
spambase = pd.read_csv('./Downloads/spambase(1).data')

In [3]:
spambase.shape

(4601, 58)

In [34]:
x1 = spambase['1']
x2 = spambase['2']
x3 = spambase['3']
x4 = spambase['4']
x5 = spambase['5']
x6 = spambase['6']
x7 = spambase['7']
x8 = spambase['8']
x9 = spambase['9']
x10 = spambase['10']
x11 = spambase['11']
x12 = spambase['12']
x13 = spambase['13']
x14 = spambase['14']
x15 = spambase['15']
x16 = spambase['16']
x17 = spambase['17']
x18 = spambase['18']
x19 = spambase['19']
x20 = spambase['20']
x21 = spambase['21']
x22 = spambase['22']
x23 = spambase['23']
x24 = spambase['24']
x25 = spambase['25']
x26 = spambase['26']
x27 = spambase['27']
x28 = spambase['28']
x29 = spambase['29']
x30 = spambase['30']
x31 = spambase['31']
x32 = spambase['32']
x33 = spambase['33']
x34 = spambase['34']
x35 = spambase['35']
x36 = spambase['36']
x37 = spambase['37']
x38 = spambase['38']
x39 = spambase['39']
x40 = spambase['40']
x41 = spambase['41']
x42 = spambase['42']
x43 = spambase['43']
x44 = spambase['44']
x45 = spambase['45']
x46 = spambase['46']
x47 = spambase['47']
x48 = spambase['48']
x49 = spambase['49']
x50 = spambase['50']
x51 = spambase['51']
x52 = spambase['52']
x53 = spambase['53']
x54 = spambase['54']
x55 = spambase['55']
x56 = spambase['56']
x57 = spambase['57']
Y = np.array([spambase['58']])
X = np.array([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57])
x = X.T
y = Y.T
x.shape,y.shape

((4601, 57), (4601, 1))

In [35]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

In [36]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3082, 57), (1519, 57), (3082, 1), (1519, 1))

In [37]:
mean = np.mean(X_train, axis = 0)
std = np.std(X_train, axis = 0, ddof = 1)
meanT = np.mean(X_test, axis = 0)
stdT = np.std(X_test, axis = 0, ddof = 1)

In [38]:
normX , normXT= (X_train-mean)/std, (X_test-meanT)/stdT

In [42]:
eta = 0.01
max_iterations = 1500
m = 3082
theta = np.random.randn(58,1)
theta

array([[-0.29787054],
       [-0.09329559],
       [ 1.4259302 ],
       [ 1.33607676],
       [-0.14826915],
       [ 0.94528354],
       [ 0.06578327],
       [ 1.12272294],
       [-1.6958264 ],
       [ 0.62224615],
       [ 1.19351603],
       [-0.04594862],
       [-0.32026005],
       [-0.03686972],
       [ 1.46689062],
       [ 0.31685732],
       [-1.14935211],
       [ 0.71892489],
       [-0.35197925],
       [ 0.61206391],
       [ 0.03264754],
       [-1.64148447],
       [ 0.60721306],
       [-1.73814006],
       [-1.00700336],
       [-0.25698683],
       [-0.14193468],
       [ 1.10047759],
       [-0.48193538],
       [-0.62002637],
       [-0.36832446],
       [ 0.40775945],
       [-1.12434169],
       [-0.4613173 ],
       [-1.0698595 ],
       [-1.28604919],
       [-0.05040319],
       [ 0.82971828],
       [ 1.34006676],
       [ 1.23726442],
       [ 1.10081129],
       [-0.77492085],
       [-1.32780745],
       [-0.81618216],
       [-0.62555767],
       [ 1

In [43]:
xNew = np.c_[np.ones((3082,1)), normX]
xNewTest = np.c_[np.ones((1519,1)), normXT]
a = np.exp(-(xNew.dot(theta)))
b = y_train-(1/(1+np.exp(-(xNew.dot(theta)))))
c = xNew.T.dot(y_train-(1/(1+np.exp(-(xNew.dot(theta))))))
xNew.shape, y_train.shape, theta.shape, a.shape, b.shape, c.shape, xNewTest.shape

((3082, 58), (3082, 1), (58, 1), (3082, 1), (3082, 1), (58, 1), (1519, 58))

In [54]:
for iterations in range(max_iterations):
    gradients = 1/m * xNew.T.dot(y_train-(1/(1+np.exp(-(xNew.dot(theta))))))
    theta = theta + eta * gradients
theta.shape

(58, 1)

In [55]:
yH = xNew.dot(theta)
yHTest = xNewTest.dot(theta)

In [56]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
yHat = sigmoid(yH)
yHatTest = sigmoid(yHTest)
yHat_cls = []
yHat_clsTest = []
for i in range(yHat.size):
    if yHat[i]<0.5:
        yHat_cls.append(0)
    else:
        yHat_cls.append(1)
yPred = np.array([yHat_cls])
yT = y_train.T

for i in range(yHatTest.size):
    if yHatTest[i]<0.5:
        yHat_clsTest.append(0)
    else:
        yHat_clsTest.append(1)
yPredTest = np.array([yHat_clsTest])
yTest = y_test.T
yPred.shape, yT.shape, yT[0], yPred[0], yPredTest.shape, yTest.shape, yTest[0], yPredTest[0]

((1, 3082),
 (1, 3082),
 array([1, 0, 1, ..., 1, 0, 0]),
 array([1, 0, 1, ..., 1, 0, 0]),
 (1, 1519),
 (1, 1519),
 array([1, 0, 0, ..., 1, 0, 0]),
 array([1, 0, 0, ..., 0, 0, 0]))

In [57]:
tp = 0
tn = 0
fp = 0
fn = 0

for i in range(yT.size):
    if (yPred[0][i]==0 and yT[0][i] == 0):
        tn = tn+1
    elif (yPred[0][i]==1 and yT[0][i] == 1):
        tp = tp+1
    elif (yPred[0][i]==0 and yT[0][i] == 1):
        fp = fp+1
    elif (yPred[0][i]==1 and yT[0][i] == 0):
        fn = fn+1
tp, tn, fp, fn

(961, 1654, 237, 230)

In [58]:
tpTest = 0
tnTest = 0
fpTest = 0
fnTest = 0

for i in range(yTest.size):
    if (yPredTest[0][i]==0 and yTest[0][i] == 0):
        tnTest = tnTest+1
    elif (yPredTest[0][i]==1 and yTest[0][i] == 1):
        tpTest = tpTest+1
    elif (yPredTest[0][i]==0 and yTest[0][i] == 1):
        fpTest = fpTest+1
    elif (yPredTest[0][i]==1 and yTest[0][i] == 0):
        fnTest = fnTest+1
tpTest, tnTest, fpTest, fnTest

(495, 787, 120, 117)

In [59]:
accuracy = (tp+tn)/(tp+tn+fp+fn)
accuracyTest = (tpTest+tnTest)/(tpTest+tnTest+fpTest+fnTest)

In [60]:
recall = (tp)/(tp+fn)
recallTest = (tpTest)/(tpTest+fnTest)

In [61]:
precision = (tp)/(tp+fp)
precisionTest = (tpTest)/(tpTest+fpTest)

In [62]:
fMeasure = (2*recall*precision)/(recall+precision)
fMeasureTest = (2*recallTest*precisionTest)/(recallTest+precisionTest)
print(accuracy, recall, precision, fMeasure)
print(accuracyTest, recallTest, precisionTest, fMeasureTest)

0.8484750162232316 0.8068849706129303 0.8021702838063439 0.8045207199665132
0.8439763001974984 0.8088235294117647 0.8048780487804879 0.8068459657701711


In [63]:
from sklearn.linear_model import LogisticRegression
lgr = LogisticRegression(penalty='none', solver='lbfgs',max_iter=10000)
lgr.fit(xNew,y_train)
f = lgr.predict(xNewTest)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [64]:
f

array([1, 0, 0, ..., 1, 0, 0])

In [65]:
from sklearn.metrics import confusion_matrix
al = confusion_matrix(y_test, f.T)
al

array([[880,  24],
       [147, 468]])

In [66]:
tn1 = al[0][0]
tp1 = al[1][1]
fn1 = al[1][0]
fp1 = al[0][1]

In [67]:
accuracy1 = (tp1+tn1)/(tp1+tn1+fp1+fn1)
recall1 = (tp1)/(tp1+fn1)
precision1 = (tp1)/(tp1+fp1)
fMeasure1 = (2*recall1*precision1)/(recall1+precision1)
print(accuracy1, recall1, precision1, fMeasure1)

0.8874259381171824 0.7609756097560976 0.9512195121951219 0.8455284552845528
