In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
spambase = pd.read_csv('./Downloads/spambase(1).data')

In [3]:
x1 = spambase['1']
x2 = spambase['2']
x3 = spambase['3']
x4 = spambase['4']
x5 = spambase['5']
x6 = spambase['6']
x7 = spambase['7']
x8 = spambase['8']
x9 = spambase['9']
x10 = spambase['10']
x11 = spambase['11']
x12 = spambase['12']
x13 = spambase['13']
x14 = spambase['14']
x15 = spambase['15']
x16 = spambase['16']
x17 = spambase['17']
x18 = spambase['18']
x19 = spambase['19']
x20 = spambase['20']
x21 = spambase['21']
x22 = spambase['22']
x23 = spambase['23']
x24 = spambase['24']
x25 = spambase['25']
x26 = spambase['26']
x27 = spambase['27']
x28 = spambase['28']
x29 = spambase['29']
x30 = spambase['30']
x31 = spambase['31']
x32 = spambase['32']
x33 = spambase['33']
x34 = spambase['34']
x35 = spambase['35']
x36 = spambase['36']
x37 = spambase['37']
x38 = spambase['38']
x39 = spambase['39']
x40 = spambase['40']
x41 = spambase['41']
x42 = spambase['42']
x43 = spambase['43']
x44 = spambase['44']
x45 = spambase['45']
x46 = spambase['46']
x47 = spambase['47']
x48 = spambase['48']
x49 = spambase['49']
x50 = spambase['50']
x51 = spambase['51']
x52 = spambase['52']
x53 = spambase['53']
x54 = spambase['54']
x55 = spambase['55']
x56 = spambase['56']
x57 = spambase['57']
Y = np.array([spambase['58']])
X = np.array([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57])
x = X.T
y = Y.T
count0 = 0
count1 = 1
for j in range(y.size):
    if y[j] == 0:
        count0 = count0+1
    if y[j] == 1:
        count1 = count1+1
x.shape,y.shape, y.size, count0, count1

((4601, 57), (4601, 1), 4601, 2788, 1814)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

In [5]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape, X_test.T[0].size, X_test[0].size

((3082, 57), (1519, 57), (3082, 1), (1519, 1), 1519, 57)

In [6]:
mean = np.mean(X_train, axis = 0)
std = np.std(X_train, axis = 0, ddof = 1)
meanT = np.mean(X_test, axis = 0)
stdT = np.std(X_test, axis = 0, ddof = 1)

In [7]:
normX , normXT= (X_train-mean)/std, (X_test-meanT)/stdT
y_train.shape, normX.shape, y_test.shape, normXT.shape, normXT[0][0]

((3082, 1), (3082, 57), (1519, 1), (1519, 57), -0.012952602858236354)

In [23]:
#split training data into spam and not spam
xN0 = []
xN1 = []
for i in range(y_train.size):
    if y_train[i] == 0:
        xN0.append(normX[i])
    else:
        xN1.append(normX[i])
xN0 = np.array(xN0)
xN1 = np.array(xN1)

xN0.shape, xN1.shape, xN0[0][0], print(xN0)

[[-0.34123104 -0.16349749 -0.56090855 ... -0.12415108 -0.21882006
  -0.37094954]
 [-0.34123104 -0.16349749  0.46028669 ... -0.0131194  -0.06712824
  -0.08324997]
 [-0.34123104 -0.16349749 -0.56090855 ... -0.08153435 -0.19123973
  -0.37720388]
 ...
 [-0.34123104  0.12720854 -0.56090855 ... -0.10287952 -0.17285284
  -0.27244371]
 [-0.34123104 -0.16349749 -0.56090855 ... -0.11627545 -0.186643
  -0.26775296]
 [-0.34123104 -0.16349749 -0.56090855 ... -0.10545566 -0.21882006
  -0.43974726]]


((1884, 57), (1198, 57), -0.3412310399473486, None)

In [24]:
mean0 = np.mean(xN0, axis = 0)
std0 = np.std(xN0, axis = 0, ddof = 1)
mean1 = np.mean(xN1, axis = 0)
std1 = np.std(xN1, axis = 0, ddof = 1)

mean0.shape, std0.shape, mean1.shape, std1.shape, np.pi, print(mean0)

[-0.11333103  0.01208948 -0.1592601  -0.04697428 -0.19645629 -0.17451516
 -0.28719636 -0.15466181 -0.1852788  -0.09572727 -0.21467123 -0.01005132
 -0.1222805  -0.05271632 -0.16079441 -0.19517503 -0.20606025 -0.15805709
 -0.21772357 -0.13991047 -0.3345848  -0.07274748 -0.28117409 -0.16928081
  0.20305268  0.18342403  0.14548208  0.12449557  0.10474132  0.13734724
  0.09541615  0.08900774  0.09117907  0.08956327  0.10992352  0.09658784
  0.14218053  0.02416832  0.08930687  0.04619342  0.08039407  0.11033798
  0.10680498  0.07274217  0.10833013  0.12388728  0.03195378  0.06655982
  0.05234006  0.05839596  0.05083622 -0.1853444  -0.2510877  -0.05318961
 -0.08241363 -0.15531015 -0.19740908]


((57,), (57,), (57,), (57,), 3.141592653589793, None)

In [65]:
pSpam = count0/y.size
pNotSpam = count1/y.size
print(pSpam, pNotSpam)

0.6059552271245382 0.3942621169311019


In [51]:

e = []
f = []
for i in range(normXT.T[0].size):
    for j in range(mean0.size):
        a = 1/std0[j] * np.sqrt(2*np.pi)
        b = ((normXT[i][j] - mean0[j])**2)/2*(std0[j])
        c = np.exp(-b)
        d = a * c
        e.append(d)
    f.append(e)
    e = []
    
len(e), len(f)

g = []
h = []
for i in range(normXT.T[0].size):
    for j in range(mean1.size):
        a = 1/std1[j] * np.sqrt(2*np.pi)
        b = ((normXT[i][j] - mean1[j])**2)/2*(std1[j])
        c = np.exp(-b)
        d = a * c
        g.append(d)
    h.append(g)
    g = []
    
len(e), len(f), len(g), len(h)
    

(0, 1519, 0, 1519)

In [52]:
f = np.array(f)
h = np.array(h)
f.shape, f[0][0], h.shape, h[0][0]

((1519, 57), 2.5885736598756117, (1519, 57), 2.3880071072090487)

In [119]:
probT0 = []
for l in range (1519):
    for k in range(57):
        probY0 = pNotSpam * f[l][k]
    probT0.append(probY0)
probT0 = np.array(probT0)

probT1 = []
for l in range (1519):
    for k in range(57):
        probY1 = h[l][k]*2.15
    probT1.append(probY1)
probT1 = np.array(probT1)
probT0.shape, probT1.shape, probT0[0], probT1[0]

((1519,), (1519,), 0.4986166343650313, 0.4793033703929196)

In [120]:
print(probT0) 
print(probT1) 
print(pSpam)
print(pNotSpam)

[0.49861663 1.81841772 1.8242102  ... 1.86133202 1.23468083 1.81787164]
[0.47930337 2.42442347 2.48121517 ... 3.08590418 2.61981221 2.4192536 ]
0.6059552271245382
0.3942621169311019


In [121]:
pred = []
for index in range(probT1.size):
    if((probT1[index]*pNotSpam) > (probT0[index]*pSpam)):
        pred.append(1)
    else:
        pred.append(0)
print(pred)      

[0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 

In [122]:
tpTest = 0
tnTest = 0
fpTest = 0
fnTest = 0

for i in range(y_test.size):
    if (pred[i]==0 and y_test.T[0][i] == 0):
        tnTest = tnTest+1
    elif (pred[i]==1 and y_test.T[0][i] == 1):
        tpTest = tpTest+1
    elif (pred[i]==0 and y_test.T[0][i] == 1):
        fpTest = fpTest+1
    elif (pred[i]==1 and y_test.T[0][i] == 0):
        fnTest = fnTest+1
tpTest, tnTest, fpTest, fnTest

(390, 611, 225, 293)

In [123]:
accuracyTest = (tpTest+tnTest)/(tpTest+tnTest+fpTest+fnTest)
recallTest = (tpTest)/(tpTest+fnTest)
precisionTest = (tpTest)/(tpTest+fpTest)
fMeasureTest = (2*recallTest*precisionTest)/(recallTest+precisionTest)
print(accuracyTest, recallTest, precisionTest, fMeasureTest)

0.6589861751152074 0.5710102489019033 0.6341463414634146 0.6009244992295839


In [104]:
from sklearn.naive_bayes import GaussianNB

In [105]:
gnb = GaussianNB()

In [106]:
y_pred = gnb.fit(X_train, y_train).predict(X_test)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [107]:
print(y_pred)

[1 1 0 ... 1 0 1]


In [108]:
from sklearn.metrics import confusion_matrix
al = confusion_matrix(y_test, y_pred)
al

array([[661, 243],
       [ 36, 579]])

In [109]:
tn1 = al[0][0]
tp1 = al[1][1]
fn1 = al[1][0]
fp1 = al[0][1]
accuracy1 = (tp1+tn1)/(tp1+tn1+fp1+fn1)
recall1 = (tp1)/(tp1+fn1)
precision1 = (tp1)/(tp1+fp1)
fMeasure1 = (2*recall1*precision1)/(recall1+precision1)
print(accuracy1, recall1, precision1, fMeasure1)

0.8163265306122449 0.9414634146341463 0.7043795620437956 0.8058455114822546
