In [1]:
import numpy as np

In [2]:
x = [[-2,1],[-5,-4],[-3,1],[0,3],[-8,11],[-2,5],[1,0],[5,-1],[-1,-3],[6,1]]
print(x)

[[-2, 1], [-5, -4], [-3, 1], [0, 3], [-8, 11], [-2, 5], [1, 0], [5, -1], [-1, -3], [6, 1]]


In [3]:
x = np.array(x)
x.shape

(10, 2)

In [4]:
x_mean = np.mean(x, axis = 0)
x_mean

array([-0.9,  1.4])

In [5]:
x_std = np.std(x, axis = 0, ddof = 1)
x_std

array([4.22821213, 4.27395211])

In [6]:
x_stand = (x-x_mean)/ x_std
x_stand.shape

(10, 2)

In [7]:
cov_x = (x_stand.T @ x_stand)/10-1
print(cov_x)

[[-0.1        -1.36743596]
 [-1.36743596 -0.1       ]]


In [8]:
u,e,v  = np.linalg.svd(x_stand)
print(e)
print(v)

[3.56010669 2.3077349 ]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [18]:
e,v  = np.linalg.eig(cov_x)
print(e)
print(v.T)

[ 1.26743596 -1.46743596]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [29]:
v_t = np.array([[0.70710678], [-0.70710678]])
v_t

array([[ 0.70710678],
       [-0.70710678]])

In [30]:
z = x_stand @ v_t
z

array([[-0.11778069],
       [ 0.20774133],
       [-0.2850161 ],
       [-0.11420117],
       [-2.77564962],
       [-0.77956328],
       [ 0.54937118],
       [ 1.38375846],
       [ 0.71123731],
       [ 1.22010257]])

#Part 2 LDA

In [31]:
class1 = np.array([[-2,1], [-5,-4], [-3,1], [0,3], [-8,11]])
class2 = np.array([[-2,5], [1,0], [5,-1], [-1,-3], [6,1]])
class1, class2

(array([[-2,  1],
        [-5, -4],
        [-3,  1],
        [ 0,  3],
        [-8, 11]]), array([[-2,  5],
        [ 1,  0],
        [ 5, -1],
        [-1, -3],
        [ 6,  1]]))

In [33]:
class1_mean = np.mean(class1, axis = 0)
class2_mean = np.mean(class2, axis = 0)
class1_mean, class2_mean

(array([-3.6,  2.4]), array([1.8, 0.4]))

In [34]:
class1_std = np.std(class1, axis = 0, ddof =1)
class2_std = np.std(class2, axis = 0, ddof =1)
class1_std, class2_std

(array([3.04959014, 5.45893763]), array([3.56370594, 2.96647939]))

In [35]:
class1_stand = (class1 - class1_mean)/ class1_std
class2_stand = (class2 - class2_mean)/ class2_std
class2_stand, class1_stand

(array([[-1.06630571,  1.55065968],
        [-0.22448541, -0.13483997],
        [ 0.89794165, -0.4719399 ],
        [-0.78569895, -1.14613977],
        [ 1.17854842,  0.20225996]]), array([[ 0.52466067, -0.25646016],
        [-0.45907809, -1.17238929],
        [ 0.19674775, -0.25646016],
        [ 1.1804865 ,  0.1099115 ],
        [-1.44281684,  1.57539811]]))

In [36]:
mean1 = np.mean(class1_stand, axis = 0) 
mean2 = np.mean(class2_stand, axis = 0)
std1_square = (5-1) * (class1_stand.T @ class1_stand)
std2_square = (5-1) * (class2_stand.T @ class2_stand)
print(mean1)
print(mean2)
print(std1_square)
print(std2_square)

[0. 0.]
[0.00000000e+00 5.55111512e-18]
[[16.         -7.16022466]
 [-7.16022466 16.        ]]
[[16.         -3.63235283]
 [-3.63235283 16.        ]]


In [37]:
sw = std1_square + std2_square
sw_inverse = np.linalg.inv(sw)
mean_diff = np.array([0, -(mean2[1])])
mean_diff_transpose = np.array([[0], [-(mean2[1])]])
print(sw)
print(sw_inverse)
print(mean_diff_transpose)
print(mean_diff)

[[ 32.        -10.7925775]
 [-10.7925775  32.       ]]
[[0.03526092 0.01189238]
 [0.01189238 0.03526092]]
[[ 0.00000000e+00]
 [-5.55111512e-18]]
[ 0.00000000e+00 -5.55111512e-18]


In [38]:
mean_diff_transpose.shape, mean_diff.shape

((2, 1), (2,))

In [39]:
sb = mean_diff_transpose @ mean_diff_transpose.T
sb

array([[0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.08148791e-35]])

In [40]:
e2, v2 = np.linalg.eig(sw_inverse * sb)
print(e2)
print(v2)

[0.000000e+00 1.086561e-36]
[[1. 0.]
 [0. 1.]]


In [41]:
W1 = np.array([[0], [1]])
W1.shape

(2, 1)

In [43]:
z1 = class1_stand @ W1
print(z1)

[[-0.25646016]
 [-1.17238929]
 [-0.25646016]
 [ 0.1099115 ]
 [ 1.57539811]]


In [44]:
z2 = class2_stand @ W1
print(z2)

[[ 1.55065968]
 [-0.13483997]
 [-0.4719399 ]
 [-1.14613977]
 [ 0.20225996]]
